#ifndef SYBEROSVERSION_GLOBAL_H
#define SYBEROSVERSION_GLOBAL_H

#include <QtGlobal>

#if defined(SYBEROSVERSION_LIBRARY)
#  define SYBEROSVERSIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYBEROSVERSIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYBEROSVERSION_GLOBAL_H
