#ifndef SYBEROSDEVICE_GLOBAL_H
#define SYBEROSDEVICE_GLOBAL_H

#include <QtGlobal>

#if defined(SYBEROSDEVICE_LIBRARY)
#  define SYBEROSDEVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYBEROSDEVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYBEROSDEVICE_GLOBAL_H
